export const data = {
  profile: "profile",
  about: "about",
  project: "project",
  setting: "settings",
  header1: "aboud",
  header2: "project",
  header3: "change language",
  langEnglish: "🇬🇧 english",
  langIndonesian: "🇮🇩 indonesian",
  langJapanese: "🇯🇵 jepanese",
  langMalay: "🇲🇾 malay",
  empty: "none",
  //----------------opsional-----------------
  paragraf001: "",
  paragraf002: "",
  paragraf003: "",
  paragraf004: "",
  paragraf005: "",
  paragraf006: "",
  paragraf007: "",
  paragraf008: "",
  paragraf009: "",
  paragraf0010: "",
}