export const data = {
  profile: "profil",
  about: "tentang",
  project: "projek",
  setting: "pengaturan",
  header1: "tentang",
  header2: "projek",
  header3: "ganti bahasa",
  langEnglish: "🇬🇧 bahasa inggris",
  langIndonesian: "🇮🇩 bahasa indonesia",
  langJapanese: "🇯🇵 bahasa jepang",
  langMalay: "🇲🇾 bahasa melayu",
  empty: "tidak ada",
  //----------------opsional-----------------
  paragraf001: "",
  paragraf002: "",
  paragraf003: "",
  paragraf004: "",
  paragraf005: "",
  paragraf006: "",
  paragraf007: "",
  paragraf008: "",
  paragraf009: "",
  paragraf0010: "",
}