export const data = {
  profile: "プロフィール",
  about: "概要",
  project: "プロジェクト",
  setting: "設定",
  header1: "概要",
  header2: "プロジェクト",
  header3: "言語を変更",
  langEnglish: "🇬🇧 英語",
  langIndonesian: "🇮🇩 インドネシア語",
  langJapanese: "🇯🇵 日本語",
  langMalay: "🇲🇾 マレー語",
  empty: "無し",
  //----------------opsional-----------------
  paragraf001: "",
  paragraf002: "",
  paragraf003: "",
  paragraf004: "",
  paragraf005: "",
  paragraf006: "",
  paragraf007: "",
  paragraf008: "",
  paragraf009: "",
  paragraf0010: "",
}