export const data = {
  profile: "profil",
  about: "tentang",
  project: "projek",
  setting: "tetapan",
  header1: "tentang",
  header2: "projek",
  header3: "tukar bahasa",
  langEnglish: "🇬🇧 bahasa inggeris",
  langIndonesian: "🇮🇩 bahasa indonesia",
  langJapanese: "🇯🇵 bahasa jepun",
  langMalay: "🇲🇾 bahasa melayu",
  empty: "tak ada",
  //----------------opsional-----------------
  paragraf001: "",
  paragraf002: "",
  paragraf003: "",
  paragraf004: "",
  paragraf005: "",
  paragraf006: "",
  paragraf007: "",
  paragraf008: "",
  paragraf009: "",
  paragraf0010: "",
}